#include <stdio.h>
#include "debugger/debugger_types.h"

const instr_data_t disassembled_z80_opcodes[256] = {
    [0x0] = {
        .fmt = "nop",
        .size = 1,
    },
    [0x1] = {
        .fmt = "ld     bc, 0x%04x",
        .size = 3,
    },
    [0x2] = {
        .fmt = "ld     (bc), a",
        .size = 1,
    },
    [0x3] = {
        .fmt = "inc    bc",
        .size = 1,
    },
    [0x4] = {
        .fmt = "inc    b",
        .size = 1,
    },
    [0x5] = {
        .fmt = "dec    b",
        .size = 1,
    },
    [0x6] = {
        .fmt = "ld     b, 0x%x",
        .size = 2,
    },
    [0x7] = {
        .fmt = "rlca",
        .size = 1,
    },
    [0x8] = {
        .fmt = "ex     af, af'",
        .size = 1,
    },
    [0x9] = {
        .fmt = "add    hl, bc",
        .size = 1,
    },
    [0xa] = {
        .fmt = "ld     a, (bc)",
        .size = 1,
    },
    [0xb] = {
        .fmt = "dec    bc",
        .size = 1,
    },
    [0xc] = {
        .fmt = "inc    c",
        .size = 1,
    },
    [0xd] = {
        .fmt = "dec    c",
        .size = 1,
    },
    [0xe] = {
        .fmt = "ld     c, 0x%x",
        .size = 2,
    },
    [0xf] = {
        .fmt = "rrca",
        .size = 1,
    },
    [0x10] = {
        .fmt     = "djnz   0x%04x",
        .fmt_lab = "djnz   %s",
        .size  = 2,
        .label = 1,
    },
    [0x11] = {
        .fmt = "ld     de, 0x%04x",
        .size = 3,
    },
    [0x12] = {
        .fmt = "ld     (de), a",
        .size = 1,
    },
    [0x13] = {
        .fmt = "inc    de",
        .size = 1,
    },
    [0x14] = {
        .fmt = "inc    d",
        .size = 1,
    },
    [0x15] = {
        .fmt = "dec    d",
        .size = 1,
    },
    [0x16] = {
        .fmt = "ld     d, 0x%x",
        .size = 2,
    },
    [0x17] = {
        .fmt = "rla",
        .size = 1,
    },
    [0x18] = {
        .fmt     = "jr     0x%04x",
        .fmt_lab = "jr     %s",
        .size  = 2,
        .label = 1,
    },
    [0x19] = {
        .fmt = "add    hl, de",
        .size = 1,
    },
    [0x1a] = {
        .fmt = "ld     a,(de)",
        .size = 1,
    },
    [0x1b] = {
        .fmt = "dec    de",
        .size = 1,
    },
    [0x1c] = {
        .fmt = "inc    e",
        .size = 1,
    },
    [0x1d] = {
        .fmt = "dec    e",
        .size = 1,
    },
    [0x1e] = {
        .fmt = "ld     e, 0x%x",
        .size = 2,
    },
    [0x1f] = {
        .fmt = "rra",
        .size = 1,
    },
    [0x20] = {
        .fmt     = "jr     nz, 0x%04x",
        .fmt_lab = "jr     nz, %s",
        .size  = 2,
        .label = 1,
    },
    [0x21] = {
        .fmt = "ld     hl, 0x%04x",
        .size = 3,
    },
    [0x22] = {
        .fmt     = "ld     (0x%04x), hl",
        .fmt_lab = "ld     (%s), hl",
        .size  = 3,
        .label = 1,
    },
    [0x23] = {
        .fmt = "inc    hl",
        .size = 1,
    },
    [0x24] = {
        .fmt = "inc    h",
        .size = 1,
    },
    [0x25] = {
        .fmt = "dec    h",
        .size = 1,
    },
    [0x26] = {
        .fmt = "ld     h, 0x%x",
        .size = 2,
    },
    [0x27] = {
        .fmt = "daa",
        .size = 1,
    },
    [0x28] = {
        .fmt     = "jr     z, 0x%04x",
        .fmt_lab = "jr     z, %s",
        .size  = 2,
        .label = 1,
    },
    [0x29] = {
        .fmt = "add    hl, hl",
        .size = 1,
    },
    [0x2a] = {
        .fmt     = "ld     hl, (0x%04x)",
        .fmt_lab = "ld     hl, (%s)",
        .size  = 3,
        .label = 1,
    },
    [0x2b] = {
        .fmt = "dec    hl",
        .size = 1,
    },
    [0x2c] = {
        .fmt = "inc    l",
        .size = 1,
    },
    [0x2d] = {
        .fmt = "dec    l",
        .size = 1,
    },
    [0x2e] = {
        .fmt = "ld     l, 0x%x",
        .size = 2,
    },
    [0x2f] = {
        .fmt = "cpl",
        .size = 1,
    },
    [0x30] = {
        .fmt     = "jr     nc, 0x%04x",
        .fmt_lab = "jr     nc, %s",
        .size  = 2,
        .label = 1,
    },
    [0x31] = {
        .fmt = "ld     sp, 0x%04x",
        .size = 3,
    },
    [0x32] = {
        .fmt     = "ld     (0x%04x), a",
        .fmt_lab = "ld     (%s), a",
        .size  = 3,
        .label = 1,
    },
    [0x33] = {
        .fmt = "inc    sp",
        .size = 1,
    },
    [0x34] = {
        .fmt = "inc    (hl)",
        .size = 1,
    },
    [0x35] = {
        .fmt = "dec    (hl)",
        .size = 1,
    },
    [0x36] = {
        .fmt = "ld     (hl), 0x%x",
        .size = 2,
    },
    [0x37] = {
        .fmt = "scf",
        .size = 1,
    },
    [0x38] = {
        .fmt     = "jr     c, 0x%04x",
        .fmt_lab = "jr     c, %s",
        .size  = 2,
        .label = 1,
    },
    [0x39] = {
        .fmt = "add    hl, sp",
        .size = 1,
    },
    [0x3a] = {
        .fmt     = "ld     a, (0x%04x)",
        .fmt_lab = "ld     a, (%s)",
        .size  = 3,
        .label = 1,
    },
    [0x3b] = {
        .fmt = "dec    sp",
        .size = 1,
    },
    [0x3c] = {
        .fmt = "inc    a",
        .size = 1,
    },
    [0x3d] = {
        .fmt = "dec    a",
        .size = 1,
    },
    [0x3e] = {
        .fmt = "ld     a, 0x%x",
        .size = 2,
    },
    [0x3f] = {
        .fmt = "ccf",
        .size = 1,
    },
    [0x40] = {
        .fmt = "ld     b, b",
        .size = 1,
    },
    [0x41] = {
        .fmt = "ld     b, c",
        .size = 1,
    },
    [0x42] = {
        .fmt = "ld     b, d",
        .size = 1,
    },
    [0x43] = {
        .fmt = "ld     b, e",
        .size = 1,
    },
    [0x44] = {
        .fmt = "ld     b, h",
        .size = 1,
    },
    [0x45] = {
        .fmt = "ld     b, l",
        .size = 1,
    },
    [0x46] = {
        .fmt = "ld     b, (hl)",
        .size = 1,
    },
    [0x47] = {
        .fmt = "ld     b, a",
        .size = 1,
    },
    [0x48] = {
        .fmt = "ld     c, b",
        .size = 1,
    },
    [0x49] = {
        .fmt = "ld     c, c",
        .size = 1,
    },
    [0x4a] = {
        .fmt = "ld     c, d",
        .size = 1,
    },
    [0x4b] = {
        .fmt = "ld     c, e",
        .size = 1,
    },
    [0x4c] = {
        .fmt = "ld     c, h",
        .size = 1,
    },
    [0x4d] = {
        .fmt = "ld     c, l",
        .size = 1,
    },
    [0x4e] = {
        .fmt = "ld     c, (hl)",
        .size = 1,
    },
    [0x4f] = {
        .fmt = "ld     c, a",
        .size = 1,
    },
    [0x50] = {
        .fmt = "ld     d, b",
        .size = 1,
    },
    [0x51] = {
        .fmt = "ld     d, c",
        .size = 1,
    },
    [0x52] = {
        .fmt = "ld     d, d",
        .size = 1,
    },
    [0x53] = {
        .fmt = "ld     d, e",
        .size = 1,
    },
    [0x54] = {
        .fmt = "ld     d, h",
        .size = 1,
    },
    [0x55] = {
        .fmt = "ld     d, l",
        .size = 1,
    },
    [0x56] = {
        .fmt = "ld     d, (hl)",
        .size = 1,
    },
    [0x57] = {
        .fmt = "ld     d, a",
        .size = 1,
    },
    [0x58] = {
        .fmt = "ld     e, b",
        .size = 1,
    },
    [0x59] = {
        .fmt = "ld     e, c",
        .size = 1,
    },
    [0x5a] = {
        .fmt = "ld     e, d",
        .size = 1,
    },
    [0x5b] = {
        .fmt = "ld     e, e",
        .size = 1,
    },
    [0x5c] = {
        .fmt = "ld     e, h",
        .size = 1,
    },
    [0x5d] = {
        .fmt = "ld     e, l",
        .size = 1,
    },
    [0x5e] = {
        .fmt = "ld     e, (hl)",
        .size = 1,
    },
    [0x5f] = {
        .fmt = "ld     e, a",
        .size = 1,
    },
    [0x60] = {
        .fmt = "ld     h, b",
        .size = 1,
    },
    [0x61] = {
        .fmt = "ld     h, c",
        .size = 1,
    },
    [0x62] = {
        .fmt = "ld     h, d",
        .size = 1,
    },
    [0x63] = {
        .fmt = "ld     h, e",
        .size = 1,
    },
    [0x64] = {
        .fmt = "ld     h, h",
        .size = 1,
    },
    [0x65] = {
        .fmt = "ld     h, l",
        .size = 1,
    },
    [0x66] = {
        .fmt = "ld     h, (hl)",
        .size = 1,
    },
    [0x67] = {
        .fmt = "ld     h, a",
        .size = 1,
    },
    [0x68] = {
        .fmt = "ld     l, b",
        .size = 1,
    },
    [0x69] = {
        .fmt = "ld     l, c",
        .size = 1,
    },
    [0x6a] = {
        .fmt = "ld     l, d",
        .size = 1,
    },
    [0x6b] = {
        .fmt = "ld     l, e",
        .size = 1,
    },
    [0x6c] = {
        .fmt = "ld     l, h",
        .size = 1,
    },
    [0x6d] = {
        .fmt = "ld     l, l",
        .size = 1,
    },
    [0x6e] = {
        .fmt = "ld     l, (hl)",
        .size = 1,
    },
    [0x6f] = {
        .fmt = "ld     l, a",
        .size = 1,
    },
    [0x70] = {
        .fmt = "ld     (hl), b",
        .size = 1,
    },
    [0x71] = {
        .fmt = "ld     (hl), c",
        .size = 1,
    },
    [0x72] = {
        .fmt = "ld     (hl), d",
        .size = 1,
    },
    [0x73] = {
        .fmt = "ld     (hl), e",
        .size = 1,
    },
    [0x74] = {
        .fmt = "ld     (hl), h",
        .size = 1,
    },
    [0x75] = {
        .fmt = "ld     (hl), l",
        .size = 1,
    },
    [0x76] = {
        .fmt = "halt",
        .size = 1,
    },
    [0x77] = {
        .fmt = "ld     (hl), a",
        .size = 1,
    },
    [0x78] = {
        .fmt = "ld     a, b",
        .size = 1,
    },
    [0x79] = {
        .fmt = "ld     a, c",
        .size = 1,
    },
    [0x7a] = {
        .fmt = "ld     a, d",
        .size = 1,
    },
    [0x7b] = {
        .fmt = "ld     a, e",
        .size = 1,
    },
    [0x7c] = {
        .fmt = "ld     a, h",
        .size = 1,
    },
    [0x7d] = {
        .fmt = "ld     a, l",
        .size = 1,
    },
    [0x7e] = {
        .fmt = "ld     a, (hl)",
        .size = 1,
    },
    [0x7f] = {
        .fmt = "ld     a, a",
        .size = 1,
    },
    [0x80] = {
        .fmt = "add    a, b",
        .size = 1,
    },
    [0x81] = {
        .fmt = "add    a, c",
        .size = 1,
    },
    [0x82] = {
        .fmt = "add    a, d",
        .size = 1,
    },
    [0x83] = {
        .fmt = "add    a, e",
        .size = 1,
    },
    [0x84] = {
        .fmt = "add    a, h",
        .size = 1,
    },
    [0x85] = {
        .fmt = "add    a, l",
        .size = 1,
    },
    [0x86] = {
        .fmt = "add    a, (hl)",
        .size = 1,
    },
    [0x87] = {
        .fmt = "add    a, a",
        .size = 1,
    },
    [0x88] = {
        .fmt = "adc    a, b",
        .size = 1,
    },
    [0x89] = {
        .fmt = "adc    a, c",
        .size = 1,
    },
    [0x8a] = {
        .fmt = "adc    a, d",
        .size = 1,
    },
    [0x8b] = {
        .fmt = "adc    a, e",
        .size = 1,
    },
    [0x8c] = {
        .fmt = "adc    a, h",
        .size = 1,
    },
    [0x8d] = {
        .fmt = "adc    a, l",
        .size = 1,
    },
    [0x8e] = {
        .fmt = "adc    a, (hl)",
        .size = 1,
    },
    [0x8f] = {
        .fmt = "adc    a, a",
        .size = 1,
    },
    [0x90] = {
        .fmt = "sub    b",
        .size = 1,
    },
    [0x91] = {
        .fmt = "sub    c",
        .size = 1,
    },
    [0x92] = {
        .fmt = "sub    d",
        .size = 1,
    },
    [0x93] = {
        .fmt = "sub    e",
        .size = 1,
    },
    [0x94] = {
        .fmt = "sub    h",
        .size = 1,
    },
    [0x95] = {
        .fmt = "sub    l",
        .size = 1,
    },
    [0x96] = {
        .fmt = "sub    (hl)",
        .size = 1,
    },
    [0x97] = {
        .fmt = "sub    a",
        .size = 1,
    },
    [0x98] = {
        .fmt = "sbc    a, b",
        .size = 1,
    },
    [0x99] = {
        .fmt = "sbc    a, c",
        .size = 1,
    },
    [0x9a] = {
        .fmt = "sbc    a, d",
        .size = 1,
    },
    [0x9b] = {
        .fmt = "sbc    a, e",
        .size = 1,
    },
    [0x9c] = {
        .fmt = "sbc    a, h",
        .size = 1,
    },
    [0x9d] = {
        .fmt = "sbc    a, l",
        .size = 1,
    },
    [0x9e] = {
        .fmt = "sbc    a, (hl)",
        .size = 1,
    },
    [0x9f] = {
        .fmt = "sbc    a, a",
        .size = 1,
    },
    [0xa0] = {
        .fmt = "and    b",
        .size = 1,
    },
    [0xa1] = {
        .fmt = "and    c",
        .size = 1,
    },
    [0xa2] = {
        .fmt = "and    d",
        .size = 1,
    },
    [0xa3] = {
        .fmt = "and    e",
        .size = 1,
    },
    [0xa4] = {
        .fmt = "and    h",
        .size = 1,
    },
    [0xa5] = {
        .fmt = "and    l",
        .size = 1,
    },
    [0xa6] = {
        .fmt = "and    (hl)",
        .size = 1,
    },
    [0xa7] = {
        .fmt = "and    a",
        .size = 1,
    },
    [0xa8] = {
        .fmt = "xor    b",
        .size = 1,
    },
    [0xa9] = {
        .fmt = "xor    c",
        .size = 1,
    },
    [0xaa] = {
        .fmt = "xor    d",
        .size = 1,
    },
    [0xab] = {
        .fmt = "xor    e",
        .size = 1,
    },
    [0xac] = {
        .fmt = "xor    h",
        .size = 1,
    },
    [0xad] = {
        .fmt = "xor    l",
        .size = 1,
    },
    [0xae] = {
        .fmt = "xor    (hl)",
        .size = 1,
    },
    [0xaf] = {
        .fmt = "xor    a",
        .size = 1,
    },
    [0xb0] = {
        .fmt = "or     b",
        .size = 1,
    },
    [0xb1] = {
        .fmt = "or     c",
        .size = 1,
    },
    [0xb2] = {
        .fmt = "or     d",
        .size = 1,
    },
    [0xb3] = {
        .fmt = "or     e",
        .size = 1,
    },
    [0xb4] = {
        .fmt = "or     h",
        .size = 1,
    },
    [0xb5] = {
        .fmt = "or     l",
        .size = 1,
    },
    [0xb6] = {
        .fmt = "or     (hl)",
        .size = 1,
    },
    [0xb7] = {
        .fmt = "or     a",
        .size = 1,
    },
    [0xb8] = {
        .fmt = "cp     b",
        .size = 1,
    },
    [0xb9] = {
        .fmt = "cp     c",
        .size = 1,
    },
    [0xba] = {
        .fmt = "cp     d",
        .size = 1,
    },
    [0xbb] = {
        .fmt = "cp     e",
        .size = 1,
    },
    [0xbc] = {
        .fmt = "cp     h",
        .size = 1,
    },
    [0xbd] = {
        .fmt = "cp     l",
        .size = 1,
    },
    [0xbe] = {
        .fmt = "cp     (hl)",
        .size = 1,
    },
    [0xbf] = {
        .fmt = "cp     a",
        .size = 1,
    },
    [0xc0] = {
        .fmt = "ret    nz",
        .size = 1,
    },
    [0xc1] = {
        .fmt = "pop    bc",
        .size = 1,
    },
    [0xc2] = {
        .fmt     = "jp     nz, 0x%04x",
        .fmt_lab = "jp     nz, %s",
        .size  = 3,
        .label = 1,
    },
    [0xc3] = {
        .fmt     = "jp     0x%04x",
        .fmt_lab = "jp     %s",
        .size  = 3,
        .label = 1,
    },
    [0xc4] = {
        .fmt     = "call   nz, 0x%04x",
        .fmt_lab = "call   nz, %s",
        .size  = 3,
        .label = 1,
    },
    [0xc5] = {
        .fmt = "push   bc",
        .size = 1,
    },
    [0xc6] = {
        .fmt = "add    a, 0x%x",
        .size = 2,
    },
    [0xc7] = {
        .fmt = "rst    00",
        .size = 1,
    },
    [0xc8] = {
        .fmt = "ret    z",
        .size = 1,
    },
    [0xc9] = {
        .fmt = "ret",
        .size = 1,
    },
    [0xca] = {
        .fmt     = "jp     z, 0x%04x",
        .fmt_lab = "jp     z, %s",
        .size  = 3,
        .label = 1,
    },
    [0xcc] = {
        .fmt     = "call   z, 0x%04x",
        .fmt_lab = "call   z, %s",
        .size  = 3,
        .label = 1,
    },
    [0xcd] = {
        .fmt     = "call   0x%04x",
        .fmt_lab = "call   %s",
        .size  = 3,
        .label = 1,
    },
    [0xce] = {
        .fmt = "adc    a, 0x%x",
        .size = 2,
    },
    [0xcf] = {
        .fmt = "rst    08",
        .size = 1,
    },
    [0xd0] = {
        .fmt = "ret    nc",
        .size = 1,
    },
    [0xd1] = {
        .fmt = "pop    de",
        .size = 1,
    },
    [0xd2] = {
        .fmt     = "jp     nc, 0x%04x",
        .fmt_lab = "jp     nc, %s",
        .size  = 3,
        .label = 1,
    },
    [0xd3] = {
        .fmt = "out    (0x%x), a",
        .size = 2,
    },
    [0xd4] = {
        .fmt     = "call   nc, 0x%04x",
        .fmt_lab = "call   nc, %s",
        .size  = 3,
        .label = 1,
    },
    [0xd5] = {
        .fmt = "push   de",
        .size = 1,
    },
    [0xd6] = {
        .fmt = "sub    0x%x",
        .size = 2,
    },
    [0xd7] = {
        .fmt = "rst    10",
        .size = 1,
    },
    [0xd8] = {
        .fmt = "ret    c",
        .size = 1,
    },
    [0xd9] = {
        .fmt = "exx",
        .size = 1,
    },
    [0xda] = {
        .fmt     = "jp     c, 0x%04x",
        .fmt_lab = "jp     c, %s",
        .size  = 3,
        .label = 1,
    },
    [0xdb] = {
        .fmt = "in     a, (0x%x)",
        .size = 2,
    },
    [0xdc] = {
        .fmt     = "call   c, 0x%04x",
        .fmt_lab = "call   c, %s",
        .size  = 3,
        .label = 1,
    },
    [0xde] = {
        .fmt = "sbc    a, 0x%x",
        .size = 2,
    },
    [0xdf] = {
        .fmt = "rst    18",
        .size = 1,
    },
    [0xe0] = {
        .fmt = "ret    po",
        .size = 1,
    },
    [0xe1] = {
        .fmt = "pop    hl",
        .size = 1,
    },
    [0xe2] = {
        .fmt     = "jp     po, 0x%04x",
        .fmt_lab = "jp     po, %s",
        .size  = 3,
        .label = 1,
    },
    [0xe3] = {
        .fmt = "ex     (sp), hl",
        .size = 1,
    },
    [0xe4] = {
        .fmt     = "call   po, 0x%04x",
        .fmt_lab = "call   po, %s",
        .size  = 3,
        .label = 1,
    },
    [0xe5] = {
        .fmt = "push   hl",
        .size = 1,
    },
    [0xe6] = {
        .fmt = "and    0x%x",
        .size = 2,
    },
    [0xe7] = {
        .fmt = "rst    20",
        .size = 1,
    },
    [0xe8] = {
        .fmt = "ret    pe",
        .size = 1,
    },
    [0xe9] = {
        .fmt = "jp     (hl)",
        .size = 1,
    },
    [0xea] = {
        .fmt     = "jp     pe, 0x%04x",
        .fmt_lab = "jp     pe, %s",
        .size  = 3,
        .label = 1,
    },
    [0xeb] = {
        .fmt = "ex     de, hl",
        .size = 1,
    },
    [0xec] = {
        .fmt     = "call   pe, 0x%04x",
        .fmt_lab = "call   pe, %s",
        .size  = 3,
        .label = 1,
    },
    [0xee] = {
        .fmt = "xor    0x%x",
        .size = 2,
    },
    [0xef] = {
        .fmt = "rst    28",
        .size = 1,
    },
    [0xf0] = {
        .fmt = "ret    p",
        .size = 1,
    },
    [0xf1] = {
        .fmt = "pop    af",
        .size = 1,
    },
    [0xf2] = {
        .fmt     = "jp     p, 0x%04x",
        .fmt_lab = "jp     p, %s",
        .size  = 3,
        .label = 1,
    },
    [0xf3] = {
        .fmt = "di",
        .size = 1,
    },
    [0xf4] = {
        .fmt     = "call   p, 0x%04x",
        .fmt_lab = "call   p, %s",
        .size  = 3,
        .label = 1,
    },
    [0xf5] = {
        .fmt = "push   af",
        .size = 1,
    },
    [0xf6] = {
        .fmt = "or     0x%x",
        .size = 2,
    },
    [0xf7] = {
        .fmt = "rst    30",
        .size = 1,
    },
    [0xf8] = {
        .fmt = "ret    m",
        .size = 1,
    },
    [0xf9] = {
        .fmt = "ld     sp, hl",
        .size = 1,
    },
    [0xfa] = {
        .fmt     = "jp     m, 0x%04x",
        .fmt_lab = "jp     m, %s",
        .size  = 3,
        .label = 1,
    },
    [0xfb] = {
        .fmt = "ei",
        .size = 1,
    },
    [0xfc] = {
        .fmt     = "call   m, 0x%04x",
        .fmt_lab = "call   m, %s",
        .size  = 3,
        .label = 1,
    },
    [0xfe] = {
        .fmt = "cp     0x%x",
        .size = 2,
    },
    [0xff] = {
        .fmt = "rst    38",
        .size = 1,
    },
};

const instr_data_t disassembled_ed_opcodes[256] = {
    [0x57] = { .fmt = "ld     a, i"  , .size = 2 },
    [0x5f] = { .fmt = "ld     a, r"  , .size = 2 },
    [0x47] = { .fmt = "ld     i, a"  , .size = 2 },
    [0x4f] = { .fmt = "ld     r, a"  , .size = 2 },
    [0x4a] = { .fmt = "adc    hl, bc", .size = 2 },
    [0x5a] = { .fmt = "adc    hl, de", .size = 2 },
    [0x6a] = { .fmt = "adc    hl, hl", .size = 2 },
    [0x7a] = { .fmt = "adc    hl, sp", .size = 2 },
    [0x42] = { .fmt = "sbc    hl, bc", .size = 2 },
    [0x52] = { .fmt = "sbc    hl, de", .size = 2 },
    [0x62] = { .fmt = "sbc    hl, hl", .size = 2 },
    [0x72] = { .fmt = "sbc    hl, sp", .size = 2 },
    [0x6f] = { .fmt = "rld" , .size = 2 },
    [0x4d] = { .fmt = "reti", .size = 2 },
    [0x45] = { .fmt = "retn", .size = 2 },
    [0x67] = { .fmt = "rrd" , .size = 2 },
    [0x44] = { .fmt = "neg" , .size = 2 },
    [0x46] = { .fmt = "im 0", .size = 2 },
    [0x56] = { .fmt = "im 1", .size = 2 },
    [0x5e] = { .fmt = "im 2", .size = 2 },
    [0xa0] = { .fmt = "ldi" , .size = 2 },
    [0xb0] = { .fmt = "ldir", .size = 2 },
    [0xa8] = { .fmt = "ldd" , .size = 2 },
    [0xb8] = { .fmt = "lddr", .size = 2 },
    [0xa1] = { .fmt = "cpi" , .size = 2 },
    [0xb1] = { .fmt = "cpir", .size = 2 },
    [0xa9] = { .fmt = "cpd" , .size = 2 },
    [0xb9] = { .fmt = "cpdr", .size = 2 },
    /*IN-related */
    [0x40] = { .fmt = "in     b, (c)", .size = 2 },
    [0x48] = { .fmt = "in     c, (c)", .size = 2 },
    [0x50] = { .fmt = "in     d, (c)", .size = 2 },
    [0x58] = { .fmt = "in     e, (c)", .size = 2 },
    [0x60] = { .fmt = "in     h, (c)", .size = 2 },
    [0x68] = { .fmt = "in     l, (c)", .size = 2 },
    [0x78] = { .fmt = "in     a, (c)", .size = 2 },
    [0xa2] = { .fmt = "ini" , .size = 2 },
    [0xb2] = { .fmt = "inir", .size = 2 },
    [0xaa] = { .fmt = "ind" , .size = 2 },
    [0xba] = { .fmt = "indr", .size = 2 },
    /* OUT-related */
    [0x41] = { .fmt = "out    (c), b", .size = 2 },
    [0x49] = { .fmt = "out    (c), c", .size = 2 },
    [0x51] = { .fmt = "out    (c), d", .size = 2 },
    [0x59] = { .fmt = "out    (c), e", .size = 2 },
    [0x61] = { .fmt = "out    (c), h", .size = 2 },
    [0x69] = { .fmt = "out    (c), l", .size = 2 },
    [0x79] = { .fmt = "out    (c), a", .size = 2 },
    [0xa3] = { .fmt = "outi", .size = 2 },
    [0xb3] = { .fmt = "otir", .size = 2 },
    [0xab] = { .fmt = "outd", .size = 2 },
    [0xbb] = { .fmt = "otdr", .size = 2 },
    /* Undocumented */
    [0x64] = { .fmt = "neg",  .size = 2 },
    [0x65] = { .fmt = "retn", .size = 2 },
    [0x66] = { .fmt = "im 0", .size = 2 },
    [0x4c] = { .fmt = "neg", .size = 2 },
    [0x6c] = { .fmt = "neg", .size = 2 },
    [0x6d] = { .fmt = "retn", .size = 2 },
    [0x4e] = { .fmt = "im 0", .size = 2 },
    [0x6e] = { .fmt = "im 0", .size = 2 },
    [0x70] = { .fmt = "in     (c)",   .size = 2 },
    [0x71] = { .fmt = "out    (c),0", .size = 2 },
    [0x54] = { .fmt = "neg",  .size = 2 },
    [0x74] = { .fmt = "neg",  .size = 2 },
    [0x55] = { .fmt = "retn", .size = 2 },
    [0x75] = { .fmt = "retn", .size = 2 },
    [0x76] = { .fmt = "im 1", .size = 2 },
    [0x77] = { .fmt = "nop",  .size = 2 },
    [0x5c] = { .fmt = "neg",  .size = 2 },
    [0x7c] = { .fmt = "neg",  .size = 2 },
    [0x5d] = { .fmt = "retn", .size = 2 },
    [0x7d] = { .fmt = "retn", .size = 2 },
    [0x7e] = { .fmt = "im 2", .size = 2 },
    [0x7f] = { .fmt = "nop",  .size = 2  },
};


const instr_data_t disassembled_cb_opcodes[256] = {
    [0x00] = { .fmt = "rlc    b", .size = 2 },
    [0x01] = { .fmt = "rlc    c", .size = 2 },
    [0x02] = { .fmt = "rlc    d", .size = 2 },
    [0x03] = { .fmt = "rlc    e", .size = 2 },
    [0x04] = { .fmt = "rlc    h", .size = 2 },
    [0x05] = { .fmt = "rlc    l", .size = 2 },
    [0x06] = { .fmt = "rlc    (hl)", .size = 2 },
    [0x07] = { .fmt = "rlc    a", .size = 2 },
    [0x08] = { .fmt = "rrc    b", .size = 2 },
    [0x09] = { .fmt = "rrc    c", .size = 2 },
    [0x0a] = { .fmt = "rrc    d", .size = 2 },
    [0x0b] = { .fmt = "rrc    e", .size = 2 },
    [0x0c] = { .fmt = "rrc    h", .size = 2 },
    [0x0d] = { .fmt = "rrc    l", .size = 2 },
    [0x0e] = { .fmt = "rrc    (hl)", .size = 2 },
    [0x0f] = { .fmt = "rrc    a", .size = 2 },
    [0x10] = { .fmt = "rl     b", .size = 2 },
    [0x11] = { .fmt = "rl     c", .size = 2 },
    [0x12] = { .fmt = "rl     d", .size = 2 },
    [0x13] = { .fmt = "rl     e", .size = 2 },
    [0x14] = { .fmt = "rl     h", .size = 2 },
    [0x15] = { .fmt = "rl     l", .size = 2 },
    [0x16] = { .fmt = "rl     (hl)", .size = 2 },
    [0x17] = { .fmt = "rl     a", .size = 2 },
    [0x18] = { .fmt = "rr     b", .size = 2 },
    [0x19] = { .fmt = "rr     c", .size = 2 },
    [0x1a] = { .fmt = "rr     d", .size = 2 },
    [0x1b] = { .fmt = "rr     e", .size = 2 },
    [0x1c] = { .fmt = "rr     h", .size = 2 },
    [0x1d] = { .fmt = "rr     l", .size = 2 },
    [0x1e] = { .fmt = "rr     (hl)", .size = 2 },
    [0x1f] = { .fmt = "rr     a", .size = 2 },
    [0x20] = { .fmt = "sla    b", .size = 2 },
    [0x21] = { .fmt = "sla    c", .size = 2 },
    [0x22] = { .fmt = "sla    d", .size = 2 },
    [0x23] = { .fmt = "sla    e", .size = 2 },
    [0x24] = { .fmt = "sla    h", .size = 2 },
    [0x25] = { .fmt = "sla    l", .size = 2 },
    [0x26] = { .fmt = "sla    (hl)", .size = 2 },
    [0x27] = { .fmt = "sla    a", .size = 2 },
    [0x28] = { .fmt = "sra    b", .size = 2 },
    [0x29] = { .fmt = "sra    c", .size = 2 },
    [0x2a] = { .fmt = "sra    d", .size = 2 },
    [0x2b] = { .fmt = "sra    e", .size = 2 },
    [0x2c] = { .fmt = "sra    h", .size = 2 },
    [0x2d] = { .fmt = "sra    l", .size = 2 },
    [0x2e] = { .fmt = "sra    (hl)", .size = 2 },
    [0x2f] = { .fmt = "sra    a", .size = 2 },
    [0x30] = { .fmt = "sll    b", .size = 2 },
    [0x31] = { .fmt = "sll    c", .size = 2 },
    [0x32] = { .fmt = "sll    d", .size = 2 },
    [0x33] = { .fmt = "sll    e", .size = 2 },
    [0x34] = { .fmt = "sll    h", .size = 2 },
    [0x35] = { .fmt = "sll    l", .size = 2 },
    [0x36] = { .fmt = "sll    (hl)", .size = 2 },
    [0x37] = { .fmt = "sll    a", .size = 2 },
    [0x38] = { .fmt = "srl    b", .size = 2 },
    [0x39] = { .fmt = "srl    c", .size = 2 },
    [0x3a] = { .fmt = "srl    d", .size = 2 },
    [0x3b] = { .fmt = "srl    e", .size = 2 },
    [0x3c] = { .fmt = "srl    h", .size = 2 },
    [0x3d] = { .fmt = "srl    l", .size = 2 },
    [0x3e] = { .fmt = "srl    (hl)", .size = 2 },
    [0x3f] = { .fmt = "srl    a", .size = 2 },
    [0x40] = { .fmt = "bit    0", .size = 2 },
    [0x41] = { .fmt = "bit    0", .size = 2 },
    [0x42] = { .fmt = "bit    0", .size = 2 },
    [0x43] = { .fmt = "bit    0", .size = 2 },
    [0x44] = { .fmt = "bit    0", .size = 2 },
    [0x45] = { .fmt = "bit    0", .size = 2 },
    [0x46] = { .fmt = "bit    0, (hl)", .size = 2 },
    [0x47] = { .fmt = "bit    0", .size = 2 },
    [0x48] = { .fmt = "bit    1", .size = 2 },
    [0x49] = { .fmt = "bit    1", .size = 2 },
    [0x4a] = { .fmt = "bit    1", .size = 2 },
    [0x4b] = { .fmt = "bit    1", .size = 2 },
    [0x4c] = { .fmt = "bit    1", .size = 2 },
    [0x4d] = { .fmt = "bit    1", .size = 2 },
    [0x4e] = { .fmt = "bit    1, (hl)", .size = 2 },
    [0x4f] = { .fmt = "bit    1", .size = 2 },
    [0x50] = { .fmt = "bit    2", .size = 2 },
    [0x51] = { .fmt = "bit    2", .size = 2 },
    [0x52] = { .fmt = "bit    2", .size = 2 },
    [0x53] = { .fmt = "bit    2", .size = 2 },
    [0x54] = { .fmt = "bit    2", .size = 2 },
    [0x55] = { .fmt = "bit    2", .size = 2 },
    [0x56] = { .fmt = "bit    2, (hl)", .size = 2 },
    [0x57] = { .fmt = "bit    2", .size = 2 },
    [0x58] = { .fmt = "bit    3", .size = 2 },
    [0x59] = { .fmt = "bit    3", .size = 2 },
    [0x5a] = { .fmt = "bit    3", .size = 2 },
    [0x5b] = { .fmt = "bit    3", .size = 2 },
    [0x5c] = { .fmt = "bit    3", .size = 2 },
    [0x5d] = { .fmt = "bit    3", .size = 2 },
    [0x5e] = { .fmt = "bit    3, (hl)", .size = 2 },
    [0x5f] = { .fmt = "bit    3", .size = 2 },
    [0x60] = { .fmt = "bit    4", .size = 2 },
    [0x61] = { .fmt = "bit    4", .size = 2 },
    [0x62] = { .fmt = "bit    4", .size = 2 },
    [0x63] = { .fmt = "bit    4", .size = 2 },
    [0x64] = { .fmt = "bit    4", .size = 2 },
    [0x65] = { .fmt = "bit    4", .size = 2 },
    [0x66] = { .fmt = "bit    4,(hl)", .size = 2 },
    [0x67] = { .fmt = "bit    4", .size = 2 },
    [0x68] = { .fmt = "bit    5", .size = 2 },
    [0x69] = { .fmt = "bit    5", .size = 2 },
    [0x6a] = { .fmt = "bit    5", .size = 2 },
    [0x6b] = { .fmt = "bit    5", .size = 2 },
    [0x6c] = { .fmt = "bit    5", .size = 2 },
    [0x6d] = { .fmt = "bit    5", .size = 2 },
    [0x6e] = { .fmt = "bit    5,(hl)", .size = 2 },
    [0x6f] = { .fmt = "bit    5", .size = 2 },
    [0x70] = { .fmt = "bit    6", .size = 2 },
    [0x71] = { .fmt = "bit    6", .size = 2 },
    [0x72] = { .fmt = "bit    6", .size = 2 },
    [0x73] = { .fmt = "bit    6", .size = 2 },
    [0x74] = { .fmt = "bit    6", .size = 2 },
    [0x75] = { .fmt = "bit    6", .size = 2 },
    [0x76] = { .fmt = "bit    6,(hl)", .size = 2 },
    [0x77] = { .fmt = "bit    6", .size = 2 },
    [0x78] = { .fmt = "bit    7", .size = 2 },
    [0x79] = { .fmt = "bit    7", .size = 2 },
    [0x7a] = { .fmt = "bit    7", .size = 2 },
    [0x7b] = { .fmt = "bit    7", .size = 2 },
    [0x7c] = { .fmt = "bit    7", .size = 2 },
    [0x7d] = { .fmt = "bit    7", .size = 2 },
    [0x7e] = { .fmt = "bit    7,(hl)", .size = 2 },
    [0x7f] = { .fmt = "bit    7", .size = 2 },
    [0x80] = { .fmt = "res    0", .size = 2 },
    [0x81] = { .fmt = "res    0", .size = 2 },
    [0x82] = { .fmt = "res    0", .size = 2 },
    [0x83] = { .fmt = "res    0", .size = 2 },
    [0x84] = { .fmt = "res    0", .size = 2 },
    [0x85] = { .fmt = "res    0", .size = 2 },
    [0x86] = { .fmt = "res    0,(hl)", .size = 2 },
    [0x87] = { .fmt = "res    0", .size = 2 },
    [0x88] = { .fmt = "res    1", .size = 2 },
    [0x89] = { .fmt = "res    1", .size = 2 },
    [0x8a] = { .fmt = "res    1", .size = 2 },
    [0x8b] = { .fmt = "res    1", .size = 2 },
    [0x8c] = { .fmt = "res    1", .size = 2 },
    [0x8d] = { .fmt = "res    1", .size = 2 },
    [0x8e] = { .fmt = "res    1,(hl)", .size = 2 },
    [0x8f] = { .fmt = "res    1", .size = 2 },
    [0x90] = { .fmt = "res    2", .size = 2 },
    [0x91] = { .fmt = "res    2", .size = 2 },
    [0x92] = { .fmt = "res    2", .size = 2 },
    [0x93] = { .fmt = "res    2", .size = 2 },
    [0x94] = { .fmt = "res    2", .size = 2 },
    [0x95] = { .fmt = "res    2", .size = 2 },
    [0x96] = { .fmt = "res    2,(hl)", .size = 2 },
    [0x97] = { .fmt = "res    2", .size = 2 },
    [0x98] = { .fmt = "res    3", .size = 2 },
    [0x99] = { .fmt = "res    3", .size = 2 },
    [0x9a] = { .fmt = "res    3", .size = 2 },
    [0x9b] = { .fmt = "res    3", .size = 2 },
    [0x9c] = { .fmt = "res    3", .size = 2 },
    [0x9d] = { .fmt = "res    3", .size = 2 },
    [0x9e] = { .fmt = "res    3,(hl)", .size = 2 },
    [0x9f] = { .fmt = "res    3", .size = 2 },
    [0xa0] = { .fmt = "res    4", .size = 2 },
    [0xa1] = { .fmt = "res    4", .size = 2 },
    [0xa2] = { .fmt = "res    4", .size = 2 },
    [0xa3] = { .fmt = "res    4", .size = 2 },
    [0xa4] = { .fmt = "res    4", .size = 2 },
    [0xa5] = { .fmt = "res    4", .size = 2 },
    [0xa6] = { .fmt = "res    4,(hl)", .size = 2 },
    [0xa7] = { .fmt = "res    4", .size = 2 },
    [0xa8] = { .fmt = "res    5", .size = 2 },
    [0xa9] = { .fmt = "res    5", .size = 2 },
    [0xaa] = { .fmt = "res    5", .size = 2 },
    [0xab] = { .fmt = "res    5", .size = 2 },
    [0xac] = { .fmt = "res    5", .size = 2 },
    [0xad] = { .fmt = "res    5", .size = 2 },
    [0xae] = { .fmt = "res    5,(hl)", .size = 2 },
    [0xaf] = { .fmt = "res    5", .size = 2 },
    [0xb0] = { .fmt = "res    6", .size = 2 },
    [0xb1] = { .fmt = "res    6", .size = 2 },
    [0xb2] = { .fmt = "res    6", .size = 2 },
    [0xb3] = { .fmt = "res    6", .size = 2 },
    [0xb4] = { .fmt = "res    6", .size = 2 },
    [0xb5] = { .fmt = "res    6", .size = 2 },
    [0xb6] = { .fmt = "res    6,(hl)", .size = 2 },
    [0xb7] = { .fmt = "res    6", .size = 2 },
    [0xb8] = { .fmt = "res    7", .size = 2 },
    [0xb9] = { .fmt = "res    7", .size = 2 },
    [0xba] = { .fmt = "res    7", .size = 2 },
    [0xbb] = { .fmt = "res    7", .size = 2 },
    [0xbc] = { .fmt = "res    7", .size = 2 },
    [0xbd] = { .fmt = "res    7", .size = 2 },
    [0xbe] = { .fmt = "res    7,(hl)", .size = 2 },
    [0xbf] = { .fmt = "res    7", .size = 2 },
    [0xc0] = { .fmt = "set    0", .size = 2 },
    [0xc1] = { .fmt = "set    0", .size = 2 },
    [0xc2] = { .fmt = "set    0", .size = 2 },
    [0xc3] = { .fmt = "set    0", .size = 2 },
    [0xc4] = { .fmt = "set    0", .size = 2 },
    [0xc5] = { .fmt = "set    0", .size = 2 },
    [0xc6] = { .fmt = "set    0,(hl)", .size = 2 },
    [0xc7] = { .fmt = "set    0", .size = 2 },
    [0xc8] = { .fmt = "set    1", .size = 2 },
    [0xc9] = { .fmt = "set    1", .size = 2 },
    [0xca] = { .fmt = "set    1", .size = 2 },
    [0xcb] = { .fmt = "set    1", .size = 2 },
    [0xcc] = { .fmt = "set    1", .size = 2 },
    [0xcd] = { .fmt = "set    1", .size = 2 },
    [0xce] = { .fmt = "set    1,(hl)", .size = 2 },
    [0xcf] = { .fmt = "set    1", .size = 2 },
    [0xd0] = { .fmt = "set    2", .size = 2 },
    [0xd1] = { .fmt = "set    2", .size = 2 },
    [0xd2] = { .fmt = "set    2", .size = 2 },
    [0xd3] = { .fmt = "set    2", .size = 2 },
    [0xd4] = { .fmt = "set    2", .size = 2 },
    [0xd5] = { .fmt = "set    2", .size = 2 },
    [0xd6] = { .fmt = "set    2,(hl)", .size = 2 },
    [0xd7] = { .fmt = "set    2", .size = 2 },
    [0xd8] = { .fmt = "set    3", .size = 2 },
    [0xd9] = { .fmt = "set    3", .size = 2 },
    [0xda] = { .fmt = "set    3", .size = 2 },
    [0xdb] = { .fmt = "set    3", .size = 2 },
    [0xdc] = { .fmt = "set    3", .size = 2 },
    [0xdd] = { .fmt = "set    3", .size = 2 },
    [0xde] = { .fmt = "set    3,(hl)", .size = 2 },
    [0xdf] = { .fmt = "set    3", .size = 2 },
    [0xe0] = { .fmt = "set    4", .size = 2 },
    [0xe1] = { .fmt = "set    4", .size = 2 },
    [0xe2] = { .fmt = "set    4", .size = 2 },
    [0xe3] = { .fmt = "set    4", .size = 2 },
    [0xe4] = { .fmt = "set    4", .size = 2 },
    [0xe5] = { .fmt = "set    4", .size = 2 },
    [0xe6] = { .fmt = "set    4,(hl)", .size = 2 },
    [0xe7] = { .fmt = "set    4", .size = 2 },
    [0xe8] = { .fmt = "set    5", .size = 2 },
    [0xe9] = { .fmt = "set    5", .size = 2 },
    [0xea] = { .fmt = "set    5", .size = 2 },
    [0xeb] = { .fmt = "set    5", .size = 2 },
    [0xec] = { .fmt = "set    5", .size = 2 },
    [0xed] = { .fmt = "set    5", .size = 2 },
    [0xee] = { .fmt = "set    5,(hl)", .size = 2 },
    [0xef] = { .fmt = "set    5", .size = 2 },
    [0xf0] = { .fmt = "set    6", .size = 2 },
    [0xf1] = { .fmt = "set    6", .size = 2 },
    [0xf2] = { .fmt = "set    6", .size = 2 },
    [0xf3] = { .fmt = "set    6", .size = 2 },
    [0xf4] = { .fmt = "set    6", .size = 2 },
    [0xf5] = { .fmt = "set    6", .size = 2 },
    [0xf6] = { .fmt = "set    6,(hl)", .size = 2 },
    [0xf7] = { .fmt = "set    6", .size = 2 },
    [0xf8] = { .fmt = "set    7", .size = 2 },
    [0xf9] = { .fmt = "set    7", .size = 2 },
    [0xfa] = { .fmt = "set    7", .size = 2 },
    [0xfb] = { .fmt = "set    7", .size = 2 },
    [0xfc] = { .fmt = "set    7", .size = 2 },
    [0xfd] = { .fmt = "set    7", .size = 2 },
    [0xfe] = { .fmt = "set    7,(hl)", .size = 2 },
    [0xff] = { .fmt = "set    7", .size = 2 },
};


const instr_data_t disassembled_ixiy_opcodes[256] = {
    [0x8E] = { .fmt = "adc    a,(i%c%+d)", .size = 3 },
    [0x86] = { .fmt = "add    a,(i%c%+d)", .size = 3 },
    [0x09] = { .fmt = "add    i%c,bc", .size = 2 },
    [0x19] = { .fmt = "add    i%c,de", .size = 2 },
    [0x29] = { .fmt = "add    i%c,i%c", .size = 2 },
    [0x39] = { .fmt = "add    i%c,sp", .size = 2 },
    [0xA6] = { .fmt = "and    (i%c%+d)", .size = 3 },
    [0xBE] = { .fmt = "cp     (i%c%+d)", .size = 3 },
    [0x35] = { .fmt = "dec    (i%c%+d)", .size = 3 },
    [0x2B] = { .fmt = "dec    i%c", .size = 2 },
    [0xE3] = { .fmt = "ex (sp),i%c", .size = 2 },
    [0x34] = { .fmt = "inc    (i%c%+d)", .size = 3 },
    [0x23] = { .fmt = "inc    i%c", .size = 2 },
    [0xE9] = { .fmt = "jp (i%c)", .size = 2 },
    [0x36] = { .fmt = "ld     (i%c%+d), 0x%02x", .size = 4 },
    [0x22] = { .fmt = "ld     (0x%02x%02x),i%c", .size = 4 },
    [0x7E] = { .fmt = "ld     a,(i%c%+d)", .size = 3 },
    [0x46] = { .fmt = "ld     b,(i%c%+d)", .size = 3 },
    [0x4E] = { .fmt = "ld     c,(i%c%+d)", .size = 3 },
    [0x56] = { .fmt = "ld     d,(i%c%+d)", .size = 3 },
    [0x5E] = { .fmt = "ld     e,(i%c%+d)", .size = 3 },
    [0x66] = { .fmt = "ld     h,(i%c%+d)", .size = 3 },
    [0x2A] = {
        .fmt = "ld     i%c,(0x%02x%02x)",
        .fmt_lab = "ld     i%c,(%s)",
        .size = 4,
        .label = 1,
    },
    [0x21] = { .fmt = "ld     i%c,0x%02x%02x", .size = 4 },
    [0x6E] = { .fmt = "ld     l,(i%c%+d)", .size = 3 },
    [0xF9] = { .fmt = "ld     sp,i%c", .size = 2 },
    [0xB6] = { .fmt = "or     (i%c%+d)", .size = 3 },
    [0xE1] = { .fmt = "pop    i%c", .size = 2 },
    [0xE5] = { .fmt = "push   i%c", .size = 2 },
    [0x96] = { .fmt = "sub    (i%c%+d)", .size = 3 },
    [0xAE] = { .fmt = "xor    (i%c%+d)", .size = 3 },
    [0x9E] = { .fmt = "sbc    a,(i%c%+d)", .size = 3 },

    /* Undocumented opcodes */
    [0x24] = { .fmt = "inc    i%ch", .size = 2 },
    [0x25] = { .fmt = "dec    i%ch", .size = 2 },
    [0x26] = { .fmt = "ld     i%ch, 0x%02x", .size = 3 },

    [0x2C] = { .fmt = "inc    i%cl", .size = 2 },
    [0x2D] = { .fmt = "dec    i%cl", .size = 2 },
    [0x2E] = { .fmt = "ld     i%cl, 0x%02x", .size = 3 },

    [0x44] = { .fmt = "ld     b, i%ch", .size = 2 },
    [0x45] = { .fmt = "ld     b, i%cl", .size = 2 },
    [0x4C] = { .fmt = "ld     c, i%ch", .size = 2 },
    [0x4D] = { .fmt = "ld     c, i%cl", .size = 2 },
    [0x54] = { .fmt = "ld     d, i%ch", .size = 2 },
    [0x55] = { .fmt = "ld     d, i%cl", .size = 2 },
    [0x5C] = { .fmt = "ld     e, i%ch", .size = 2 },
    [0x5D] = { .fmt = "ld     e, i%cl", .size = 2 },


    [0x60] = { .fmt = "ld     i%ch, b", .size = 2 },
    [0x61] = { .fmt = "ld     i%ch, c", .size = 2 },
    [0x62] = { .fmt = "ld     i%ch, d", .size = 2 },
    [0x63] = { .fmt = "ld     i%ch, e", .size = 2 },
    [0x64] = { .fmt = "ld     i%ch, i%ch", .size = 2 },
    [0x65] = { .fmt = "ld     i%ch, i%cl", .size = 2 },
    [0x67] = { .fmt = "ld     i%ch, a", .size = 2 },


    [0x68] = { .fmt = "ld     i%cl, b", .size = 2 },
    [0x69] = { .fmt = "ld     i%cl, c", .size = 2 },
    [0x6A] = { .fmt = "ld     i%cl, d", .size = 2 },
    [0x6B] = { .fmt = "ld     i%cl, e", .size = 2 },
    [0x6C] = { .fmt = "ld     i%cl, i%ch", .size = 2 },
    [0x6D] = { .fmt = "ld     i%cl, i%cl", .size = 2 },
    [0x6F] = { .fmt = "ld     i%cl, a", .size = 2 },



    [0x7C] = { .fmt = "ld     a, i%ch", .size = 2 },
    [0x7D] = { .fmt = "ld     a, i%cl", .size = 2 },

    [0x84] = { .fmt = "add    a, i%ch", .size = 2 },
    [0x85] = { .fmt = "add    a, i%cl", .size = 2 },
    [0x8C] = { .fmt = "adc    a, i%ch", .size = 2 },
    [0x8D] = { .fmt = "adc    a, i%cl", .size = 2 },
    [0x94] = { .fmt = "sub    i%ch", .size = 2 },
    [0x95] = { .fmt = "sub    i%cl", .size = 2 },
    [0x9C] = { .fmt = "sbc    a, i%ch", .size = 2 },
    [0x9D] = { .fmt = "sbc    a, i%cl", .size = 2 },
    [0xA4] = { .fmt = "and    i%ch", .size = 2 },
    [0xA5] = { .fmt = "and    i%cl", .size = 2 },
    [0xAC] = { .fmt = "xor    i%ch", .size = 2 },
    [0xAD] = { .fmt = "xor    i%cl", .size = 2 },
    [0xB4] = { .fmt = "or     i%ch", .size = 2 },
    [0xB5] = { .fmt = "or     i%cl", .size = 2 },
    [0xBC] = { .fmt = "cp     i%ch", .size = 2 },
    [0xBD] = { .fmt = "cp     i%cl", .size = 2 },
};
